defaultSemverRangePrefix: ''

nodeLinker: node-modules

packageExtensions:
  '@nrwl/cypress@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
  '@nrwl/devkit@*':
    peerDependencies:
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/eslint-plugin-nx@*':
    peerDependencies:
      eslint: '*'
      nx: '*'
  '@nrwl/jest@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/js@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/linter@*':
    peerDependencies:
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/next@*':
    peerDependencies:
      '@babel/core': '*'
      '@types/node': '*'
      dotenv: '*'
      eslint: '*'
      express: '*'
      nx: '*'
      tsconfig-paths-webpack-plugin: '*'
      typescript: '*'
      webpack: '*'
    peerDependenciesMeta:
      '@types/node':
        optional: true
      typescript:
        optional: true
      webpack:
        optional: true
  '@nrwl/react@*':
    peerDependencies:
      '@types/node': '*'
      stylus: '*'
      eslint: '*'
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
      stylus:
        optional: true
  '@nrwl/rollup@*':
    peerDependencies:
      '@babel/core': '*'
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/storybook@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
      webpack: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/web@*':
    peerDependencies:
      '@types/node': '*'
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      '@types/node':
        optional: true
      typescript:
        optional: true
  '@nrwl/webpack@*':
    peerDependencies:
      '@babel/core': '*'
      '@types/node': '*'
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  stylelint-config-recommended-scss@*:
    peerDependenciesMeta:
      postcss:
        optional: true

yarnPath: .yarn/releases/yarn-3.2.3.cjs
